# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
version: '3'

output: 'prefixed'

vars:
  GO_PACKAGES:
    sh: 'go list ./...'

tasks:
  default:
    deps:
      - task: 'ci'

  ci:
    cmds:
      - task: 'lint'
      - task: 'test'
    desc: 'Run all CI-related tasks'

  lint:
    cmds:
      - task: 'lint:golint'
      - task: 'lint:staticcheck'
      - task: 'lint:vet'
    desc: 'Run all linting-related tasks'

  lint:golint:
    cmds:
      - 'golint -set_exit_status {{catLines .GO_PACKAGES}}'
    desc: 'Lint Go files with Golint'

  lint:staticcheck:
    cmds:
      - 'staticcheck {{catLines .GO_PACKAGES}}'
    desc: 'Lint Go files with Staticcheck'

  lint:vet:
    cmds:
      - 'go vet {{catLines .GO_PACKAGES}}'
    desc: 'Lint Go files with Vet'

  test:
    cmds:
      - 'go test {{catLines .GO_PACKAGES}}'
    desc: 'Run tests for all solutions'
