# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
name: 'Lint and Test AoC 2021 Go Solutions'

on:
  push:
    branches:
      - 'master'

jobs:
  lint-yaml:
    name: 'Lint and Test AoC 2021 Go Solutions'
    runs-on: 'ubuntu-24.04'
    steps:
      - name: 'Check out repository'
        uses: 'actions/checkout@v2'

      - name: 'Set up Go environment'
        uses: 'actions/setup-go@v2'
        with:
          go-version: '1.17.x'

      - name: 'Install Task'
        run: 'curl -sL https://taskfile.dev/install.sh | sh'
        working-directory: './2021/golang'

      - name: 'Install Golint and Staticcheck'
        run: |
          go install golang.org/x/lint/golint@latest
          go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: 'Run all linting and testing tasks'
        run: './bin/task ci'
        working-directory: './2021/golang'
